---

- import_tasks:
    file: prepare.yml
  tags: prepare

- import_tasks:
    file: install.yml
  tags: install

- import_tasks:
    file: configure.yml
  tags: configure

- import_tasks:
    file: verify.yml
  tags: verify

